### ISSUE TITLE
TODO list for CD->SBGN

### ISSUE THREAD

**Issue by royludo** [royludo/cd2sbgnml#1]
- [x] logic gates

- _modifiers pointing to direct links (without process)_ -> abandoned, not valid SBGN

- [x] anchor points for receptors 

- [ ] and truncated proteins

- [x] reversible reactions

- [x] keep style information

- [x] keep notes

- [x] residues for NA features

- [x] style consistency for process/logic gates

- [x] clone markers

- [x] entities pointing to UNKNOWN logic gates must point directly to concerned process

- [x] MIRIAM annotations

- [ ] label location for complexes

- [ ] logic gate reactions
