### ISSUE TITLE
TODO list for SBGN -> CD

### ISSUE THREAD

**Issue by royludo** [royludo/cd2sbgnml#3]
- [x] logic gates connecting phenotypes

- [ ] open/closed states variables and associated ion channel state

- [x] notes and annotations

- [ ] annotation glyphs
